version: 0.2
 
phases:
  build:
    commands:
      - docker build -t git.systementor.se/abdilfatax/stensax424 .
      - docker login -u abdilfatax -p Tc192291 https://git.systementor.se/abdilfatax
      - docker push git.systementor.se/yacloud/stensax424
       